trigger: none

resources:
  pipelines:
    - pipeline: ci
      source: WorkforceManagementSystem
      trigger: true

pool:
  vmImage: ubuntu-latest

stages:

# =====================================
# BACKEND DEPLOYMENT
# =====================================

- stage: Deploy_Backend

  displayName: Deploy Backend API

  jobs:

    - deployment: DeployBackend

      displayName: Deploy Backend

      environment: wms-production-api

      strategy:

        runOnce:

          deploy:

            steps:

              - download: ci

                artifact: api-drop

              - task: AzureWebApp@1

                displayName: Deploy Backend App Service

                inputs:

                  azureSubscription: 'wms-service-connection'

                  appName: 'wms-api-prasanna'

                  package: '$(Pipeline.Workspace)/ci/api-drop'

# =====================================
# FRONTEND DEPLOYMENT
# =====================================

- stage: Deploy_Frontend

  displayName: Deploy Angular Frontend

  dependsOn: Deploy_Backend

  jobs:

    - deployment: DeployFrontend

      displayName: Deploy Frontend

      environment: wms-production-web

      strategy:

        runOnce:

          deploy:

            steps:

              - download: ci

                artifact: frontend-drop

              - task: AzureWebApp@1

                displayName: Deploy Frontend App Service

                inputs:

                  azureSubscription: 'wms-service-connection'

                  appName: 'wms-frontend-prasanna'

                  package: '$(Pipeline.Workspace)/ci/frontend-drop'